### ISSUE TITLE
Starting server (server.js) error

### ISSUE THREAD

**Issue by ultimo5** [Jerenaux/phaserquest#12]
Thanks for your great job. I am very interesting PQ, wanna run ASAP.  
BTW, I faced error when I start server. 

[root@localhost]# node server.js
Listening on 8081

/home/neoguru/html/pq_test/js/server/GameServer.js:84
    Object.assign(GameServer.db.entities,GameServer.db.client_entities); // me
           ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.GameServer.readMap (/home/neoguru/html/pq_test/js/server/GameServer.js:84:12)
    at Server.io.on.socket.pings (/home/neoguru/html/pq_test/server.js:85:8)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1056:10
    at process._tickCallback (node.js:458:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:945:3

I am not fix mongoDB yet. Do I have to set it first?

**Comment by Jerenaux** [comment]
It's a very strange error, [Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) is standard in Node.js, but apparently it is not recognized here. What version of Node.js are you using? This doesn't seem to be related to MondoDB in any case!

**Comment by ultimo5** [comment]
Yes, I think so. hm... 
My Node.js version is bellow.

[root@localhost]# node -v
v0.10.48

How about this case? hehe T_T

**Comment by Nerothos** [comment]
**0**.10.48? o_O
Are you sure your node version is up to date? Because the last LTS one is 10.XX.xx

**Comment by Jerenaux** [comment]
What's the status of this issue? @ultimo5 did you upgrade your Node.js?

**Comment by ultimo5** [comment]
I upgraded, but I still have been faced error. hm...
And I want to discuss with you something about this game's commercial service. 
My private email is neoguru@cosmosinfra.net. When you are free, please send me email. 

Thank you.
