### ISSUE TITLE
TypeError: GameServer.server.db.collection is not a function

### ISSUE THREAD

**Issue by marek22k** [Jerenaux/phaserquest#23]
**What have I done?**
I followed the instructions and ran node server.js.

**What happened?**
```
Listening on 8081
(node:934736) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Map read
Connection to db established
connection with ID M1nFdvQFOeBD6vjvAAAA
0 already connected
/home/marek/phaserquest/js/server/GameServer.js:268
    GameServer.server.db.collection('players').insertOne(document,function(err){
                         ^

TypeError: GameServer.server.db.collection is not a function
    at Object.GameServer.addNewPlayer (/home/marek/phaserquest/js/server/GameServer.js:268:26)
    at Socket.<anonymous> (/home/marek/phaserquest/server.js:117:16)
    at Socket.emit (events.js:314:20)
    at /home/marek/phaserquest/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by congling** [comment]
From Mongo 3.x, the connection class has been changed.

Please find code  "**mongo.connect('mongodb://'+mongoHost+'/'+mongoDBName ,function(err,db){**" in server.js and then change it to following

 mongo.connect('mongodb://'+mongoHost,function(err,client){
        if(err) throw(err);
        server.db =  client.db(mongoDBName)        
        console.log('Connection to db established');
    });

**Comment by Jerenaux** [comment]
Thanks a lot! I'll fix it ASAP but feel free to make a pull request with
the fix if you want :)

Jerome

**Comment by Jerenaux** [comment]
Fixed!
